function [fitresult, gof] = createFit_B(sb, LL, bool_plot)
%CREATEFIT(SB,LL)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : sb
%      Y Output: LL
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Apr-2020 12:39:32


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( sb, LL );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [-108.091605228192 -4.19049699982178e-05 0.00610401347865924 -16.7975359340395];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );
if bool_plot == 1
    % Plot fit with data.
    figure( 'Name', 'untitled fit 2' );
    h = plot( fitresult, xData, yData );
    legend( h, 'LL vs. sb', 'untitled fit 2', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'sb', 'Interpreter', 'none' );
    ylabel( 'LL', 'Interpreter', 'none' );
    grid on
end


